const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const core=require('../reasoning-core.js');
const keys=[{no:3},{no:7}], scope={material:core.BOOKS[0],chapter:'테스트',section:'테스트',start_no:null,end_no:null,set_code:null};
const raw=()=>({request_id:crypto.randomUUID(),items:[{n:3,reason:'첫 근거 A'},{n:7,reason:'첫 근거 B'}]});
test('only two books; non-contiguous numbers retained',()=>{assert(core.isTarget(core.BOOKS[0]));assert(core.isTarget(core.BOOKS[1]));assert(!core.isTarget('기타 교재'));assert.deepEqual(core.input(raw(),keys,false).items.map(i=>i.n),[3,7]);});
test('blank, duplicate, missing and overlong reasons rejected',()=>{for(const items of [[{n:3,reason:' '},{n:7,reason:'b'}],[{n:3,reason:'a'},{n:3,reason:'b'}],[],[{n:3,reason:'a'.repeat(1001)},{n:7,reason:'b'}]])assert.throws(()=>core.input({...raw(),items},keys,false));});
test('immutable first thoughts retained across multiple retries; cross-student and scope rejected',()=>{const id=crypto.randomUUID();const first=core.record(core.input(raw(),keys,false),scope,keys,[1,2],null,'테스트 학생',id);const parent={id,student_name:'테스트 학생',wrong_questions:[3],reasoning:first};const clean=core.input({request_id:crypto.randomUUID(),parent_id:id,items:[{n:3,reason:'새 근거',mistake:'처음 놓친 점'}]},[{no:3}],true);const second=core.record(clean,scope,[{no:3}],[3],parent,'테스트 학생',crypto.randomUUID());assert.equal(second.items[0].first_reason,'첫 근거 A');assert.throws(()=>core.record(clean,scope,[{no:3}],[3],parent,'다른 학생',crypto.randomUUID()));assert.throws(()=>core.record(clean,{...scope,material:core.BOOKS[1]},keys,[3],parent,'테스트 학생',crypto.randomUUID()));assert.throws(()=>core.record(clean,scope,keys,[1,3],parent,'테스트 학생',crypto.randomUUID()));const third=core.record(clean,scope,[{no:3}],[4],{...parent,reasoning:second},'테스트 학생',crypto.randomUUID());assert.equal(third.items[0].first_reason,'첫 근거 A');assert.equal(third.items[0].previous_reason,'새 근거');assert.equal(first.items[0].reason,'첫 근거 A');});
function app(){
 const db={submissions:[],questions:[],answer_bank:[{material:core.BOOKS[0],chapter:'테스트',section:'테스트',question_no:3,correct_answer:2,is_plus:false},{material:core.BOOKS[0],chapter:'테스트',section:'테스트',question_no:7,correct_answer:4,is_plus:false},{material:'기타 교재',chapter:'테스트',section:null,question_no:1,correct_answer:3,is_plus:false}],problem_sets:[{set_code:'TEST',title:'등록 과제',material:core.BOOKS[0],chapter:'테스트',section:'테스트'}],answer_keys:[]};
 let handler,failInsert=false;
 function from(table){let filters=[],order=null,single=false,insert=null;const q={select(){return q;},eq(k,v){filters.push(r=>r[k]===v);return q;},is(k,v){filters.push(r=>r[k]===v);return q;},gte(k,v){filters.push(r=>r[k]>=v);return q;},lte(k,v){filters.push(r=>r[k]<=v);return q;},order(k){order=k;return q;},single(){single=true;return q;},maybeSingle(){single=true;return q;},insert(row){insert=row;return q;},then(resolve,reject){if(insert){if(failInsert)return Promise.resolve({error:{code:'FAIL',message:'synthetic write failure'}}).then(resolve,reject);if(insert.reasoning_request_id&&db[table].some(r=>r.reasoning_request_id===insert.reasoning_request_id))return Promise.resolve({error:{code:'23505'}}).then(resolve,reject);db[table].push(structuredClone(insert));return Promise.resolve({error:null}).then(resolve,reject);}let rows=db[table].filter(r=>filters.every(f=>f(r)));if(order)rows.sort((a,b)=>a[order]-b[order]);return Promise.resolve({data:single?(rows[0]||null):rows,error:null}).then(resolve,reject);}};return q;}
 const context={globalThis:null,Request,Response,crypto,JSON,Map,Set,Number,String,Object,Array,Error,console,PpajakReasoningCore:core,createClient:()=>({from}),Deno:{serve(fn){handler=fn;},env:{get(){return undefined;}}}};context.globalThis=context;
 vm.runInNewContext(fs.readFileSync(__dirname+'/../server/grade.ts','utf8').replace(/^import .*;\n/gm,''),context);
 return {db,fail(){failInsert=true;},recover(){failInsert=false;},async send(body){const res=await handler(new Request('https://test.invalid',{method:'POST',body:JSON.stringify(body)}));return {status:res.status,data:await res.json()};}};
}
const base=()=>({material:core.BOOKS[0],chapter:'테스트',section:'테스트',student_name:'테스트 학생',answers:[1,4]});
test('first attempt atomic storage, idempotency, no key leakage',async()=>{const a=app(),body={...base(),reasoning:raw()},r=await a.send(body);assert.equal(r.status,200);assert.equal(r.data.score,1);assert.deepEqual(r.data.wrong_questions,[3]);assert(r.data.reasoning_saved);assert.equal(a.db.submissions.length,1);assert(!('wrong_detail'in r.data));assert(!('reasoning'in r.data));assert.equal((await a.send(body)).data.submission_id,r.data.submission_id);assert.equal(a.db.submissions.length,1);assert.equal((await a.send({...body,answers:[2,4]})).status,409);});
test('missing reasons and invalid choices never write',async()=>{const a=app();for(const body of [base(),{...base(),answers:[99,4],reasoning:raw()},{...base(),reasoning:{...raw(),items:[{n:3,reason:' '},{n:7,reason:'b'}]}}])assert.equal((await a.send(body)).status,400);assert.equal(a.db.submissions.length,0);});
test('retry requires two explanations and appends instead of overwriting',async()=>{const a=app(),first=await a.send({...base(),reasoning:raw()});const retry={...base(),answers:[2],retry_questions:[3],reasoning:{request_id:crypto.randomUUID(),parent_id:first.data.submission_id,items:[{n:3,reason:'바뀐 근거'}]}};assert.equal((await a.send(retry)).status,400);retry.reasoning.items[0].mistake='처음 놓친 점';assert.equal((await a.send(retry)).status,200);assert.equal(a.db.submissions.length,2);assert.equal(a.db.submissions[1].reasoning.items[0].first_reason,'첫 근거 A');assert.equal(a.db.submissions[0].reasoning.items[0].reason,'첫 근거 A');});
test('failed write can retry safely',async()=>{const a=app(),body={...base(),reasoning:raw()};a.fail();assert.equal((await a.send(body)).status,500);assert.equal(a.db.submissions.length,0);a.recover();assert.equal((await a.send(body)).status,200);assert.equal(a.db.submissions.length,1);});
test('registered assignments enforce reasons too',async()=>{const a=app(),body={student_name:'테스트 학생',set_code:'TEST',answers:[1,4]};assert.equal((await a.send(body)).status,400);assert.equal((await a.send({...body,reasoning:raw()})).status,200);});
test('legacy range grading, timing and question form unchanged',async()=>{const a=app(),r=await a.send({material:'기타 교재',chapter:'테스트',start_no:1,end_no:1,student_name:'테스트 학생',answers:[3],part_times:{독서:10}});assert.equal(r.status,200);assert.equal(r.data.score,1);assert.equal(r.data.reasoning_saved,false);assert.equal(a.db.submissions[0].part_times.독서,10);assert.equal((await a.send({type:'question',student_name:'테스트 학생',question:'검증 질문'})).status,200);assert.equal(a.db.questions.length,1);});
